### ISSUE TITLE
Verbose stream output does not work since 1.7.5.1

### ISSUE THREAD

**Issue by kborowinski** [MVKozlov/PoshRSJob#3]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Verbose stream output does not work since commit eeb86afd1b8ecc9b8ce1844141b96d50f592410c

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.5.2
Start-RSJob -ScriptBlock {$VerbosePreference = 'Continue'; Write-Verbose 'VerboseOutput'} | Receive-RSJob
```
**What is the expected behavior?**
```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.4.4
Start-RSJob -ScriptBlock {$VerbosePreference = 'Continue'; Write-Verbose 'VerboseOutput'} | Receive-RSJob
VERBOSE: VerboseOutput
```

**Comment by MVKozlov** [comment]
It depends :)
With your addition we always get verbose output even when we doesn't want it
```
PS C:\> $VerbosePreference
SilentlyContinue
PS C:\> start-rsjob { $VerbosePreference = 'Continue'; write-verbose verbtest }
Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
3        Job3                 Completed       False        False         $VerbosePreference = 'Continue'; wri...

PS C:\> Get-RSJob | Receive-RSJob
ПОДРОБНО: verbtest
```
and without additions
```
PS C:\> start-rsjob { $VerbosePreference = 'Continue'; write-verbose verbtest }

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
1        Job1                 Completed       False        False         $VerbosePreference = 'Continue'; wri...

PS C:\> Get-RSJob | Receive-RSJob
PS C:\> Get-RSJob | Receive-RSJob -Verbose
ПОДРОБНО: verbtest
```
we get verbose output with verbose parameter

btw, write-error also does not return any output, but it fill **Job.Error**

so let continue discussion :)

**Comment by kborowinski** [comment]
Well, it depends ;) - until PoshRSJob 1.7.5.1 one had to set *VerbosePreference* to *Continue* inside of the *Start-RSJob* scriptblock to get verbose output. If you didn't want to get verbose output you simply didn't change the *VerbosePreference*:

**Previous PoshRSJob version with verbose output:**
```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.4.4
Start-RSJob -ScriptBlock {$VerbosePreference = 'Continue'; Write-Verbose 'VerboseOutput'} | Receive-RSJob
VERBOSE: VerboseOutput
```

**Previous PoshRSJob version without verbose output:**
```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.4.4
Start-RSJob -ScriptBlock {Write-Verbose 'VerboseOutput'} | Receive-RSJob
```
**VS**

**Latest PoshRSJob version with verbose output:**
```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.5.2
Start-RSJob -ScriptBlock {$VerbosePreference = 'Continue'; Write-Verbose 'VerboseOutput'} | Receive-RSJob -Verbose
VERBOSE: VerboseOutput
```

**Latest PoshRSJob version without verbose output (option 1):**
```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.5.2
Start-RSJob -ScriptBlock {$VerbosePreference = 'Continue'; Write-Verbose 'VerboseOutput'} | Receive-RSJob
```
**Latest PoshRSJob version without verbose output (option 2):**
```PowerShell
Import-Module -Name PoshRSJob -Version 1.7.5.2
Start-RSJob -ScriptBlock {Write-Verbose 'VerboseOutput'} | Receive-RSJob
```


After my change in *WriteStream.ps1* our production code works as it used to with PoshRSJob 1.7.4.4. From version 1.7.5.1 one has to set *VerbosePreference* to *Continue* inside of the *Start-RSJob* scriptblock **AND** to specify verbose parameter with *Receive-RSJob* thus breaking our production code. I know that it's easy to fix - just always set *VerbosePreference* to *Continue* inside of the scriptblock and then specify verbose parameter with *Receive-RSJob* when needed, however our change management process is so painful and daunting that it was much easier to propose this PR than go through our CMP for all the production modules ;)

I do not press you to push this PR - I just want to express my concern that this's breaking change and may force some burden on people.

**Comment by MVKozlov** [comment]
I see your points and agree with it.
Breaking changes is evil, so I approve MR,
Is that enought for you or I must do version bump ?

**Comment by kborowinski** [comment]
Thanks mate! No version bump needed.
